In [24]:
import torch
import numpy as np

num_inputs = 2
num_examples = 1000
true_w = [2, -3.4]
true_b = 4.2
features = torch.randn(num_examples, num_inputs)
labels = true_w[0] * features[:, 0] + true_w[1] * features[:, 1] + true_b
labels += torch.normal(mean = 0, std = 0.01, size = labels.shape)

In [25]:
import torch.utils.data as Data
batch_size = 10
dataset = Data.TensorDataset(features, labels)
data_iter = Data.DataLoader(dataset, batch_size, shuffle = True)

In [26]:
for x,y in data_iter:
    print(x, y)
    break

tensor([[ 0.5456, -0.0525],
        [-0.5039,  0.6951],
        [-0.6865,  2.7087],
        [ 0.2819,  0.4835],
        [ 0.5732, -0.5314],
        [ 2.0859,  0.1860],
        [-1.9297,  0.7202],
        [ 1.3474,  1.0931],
        [-0.7696, -0.3503],
        [-0.4656,  0.2541]]) tensor([ 5.4611,  0.8407, -6.3828,  3.1226,  7.1557,  7.7371, -2.1253,  3.1908,
         3.8363,  2.4042])


In [27]:
import torch.nn as nn

class LinearNet(nn.Module):
    def __init__(self, n_feature):
        super(LinearNet, self).__init__()
        self.linear = nn.Linear(n_feature, 1)

    def forward(self, x):
        y = self.linear(x)
        return y

net = LinearNet(num_inputs)
print(net)

for param in net.parameters():
    print(param)

LinearNet(
  (linear): Linear(in_features=2, out_features=1, bias=True)
)
Parameter containing:
tensor([[-0.0934, -0.6944]], requires_grad=True)
Parameter containing:
tensor([-0.2677], requires_grad=True)


In [28]:
from torch.nn import init
init.normal_(net.linear.weight, mean = 0, std=0.01)
init.constant_(net.linear.bias, val = 0)

Parameter containing:
tensor([0.], requires_grad=True)

In [29]:
loss = nn.MSELoss()

import torch.optim as optim

optimizer = optim.SGD(net.parameters(), lr = 0.03)
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.03
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [30]:
num_epochs = 3
for epoch in range(1, num_epochs + 1):
    for x, y in  data_iter:
        output = net(x)
        l = loss(output, y.view(-1, 1))
        optimizer.zero_grad()
        l.backward()
        optimizer.step()

    print('epoch %d, loss: %f' % (epoch, l.item()))

epoch 1, loss: 0.000133
epoch 2, loss: 0.000021
epoch 3, loss: 0.000125


In [32]:
dense = net.linear
print(true_w, dense.weight)
print(true_b, dense.bias)

[2, -3.4] Parameter containing:
tensor([[ 1.9999, -3.4001]], requires_grad=True)
4.2 Parameter containing:
tensor([4.2001], requires_grad=True)
