In [19]:
import torch
import datetime,time

In [25]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [26]:
x = torch.rand(5, 3)
print(x)

tensor([[0.5496, 0.6710, 0.8952],
        [0.1435, 0.8680, 0.2177],
        [0.1973, 0.0776, 0.2831],
        [0.8004, 0.0236, 0.9872],
        [0.2035, 0.1826, 0.9255]])


In [27]:
x = torch.zeros(5, 3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [28]:
x  = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [29]:
x = x.new_ones(5 , 3, dtype=torch.double)
print(x)

x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.3351, 0.9668, 0.1396],
        [0.4462, 0.1532, 0.7050],
        [0.1188, 0.7040, 0.2374],
        [0.1843, 0.0549, 0.9406],
        [0.3552, 0.5467, 0.4900]])


In [30]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.2073, 1.5083, 0.6894],
        [1.3094, 0.2485, 1.5408],
        [0.2990, 1.3491, 0.7008],
        [0.6936, 0.8985, 1.7322],
        [0.5100, 0.7558, 0.6608]])


In [31]:
print(torch.add(x, y))

tensor([[1.2073, 1.5083, 0.6894],
        [1.3094, 0.2485, 1.5408],
        [0.2990, 1.3491, 0.7008],
        [0.6936, 0.8985, 1.7322],
        [0.5100, 0.7558, 0.6608]])


In [32]:
result =  torch.empty(5, 3)
torch.add(x, y, out = result)
print(result)

tensor([[1.2073, 1.5083, 0.6894],
        [1.3094, 0.2485, 1.5408],
        [0.2990, 1.3491, 0.7008],
        [0.6936, 0.8985, 1.7322],
        [0.5100, 0.7558, 0.6608]])


In [33]:
y.add_(x)
print(y)

tensor([[1.2073, 1.5083, 0.6894],
        [1.3094, 0.2485, 1.5408],
        [0.2990, 1.3491, 0.7008],
        [0.6936, 0.8985, 1.7322],
        [0.5100, 0.7558, 0.6608]])


In [34]:
print(x[:, 1])

tensor([0.9668, 0.1532, 0.7040, 0.0549, 0.5467])


In [35]:
x = torch.randn(4, 4)
y = x.view(16,1)
z =x.view(-1, 8)

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16, 1]) torch.Size([2, 8])


In [36]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.7503])
0.7503125667572021


In [37]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [38]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [39]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [40]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [42]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([1.7503], device='cuda:0')
tensor([1.7503], dtype=torch.float64)
